### ISSUE TITLE
m-add problem in t-log

### ISSUE THREAD

**Issue by wrdana** [someoneemily/CodeU-Summer-2017#13]
Reading from the log doesn't deal well with messages that have spaces in them (i.e. more than one word)
My Tlog is:
U-ADD 1.3684971731 dana 1498423507933
U-ADD 1.2735599698 eylon 1498423516428
C-ADD 1.1508751925 1.2735599698 1498423560835 someConversation
M-ADD 1.1577672239 1.2735599698 1.1508751925 some 1498423569163
u-M-ADD 1.4212298915 1.2735599698 1.1508751925 awesome 1498423579315
M-ADD 1.953165862 1.2735599698 1.1508751925 aaaaaaawesome conversation!!! 1498423645859

The error I'm getting when restarting the server:
**Exception in thread "main" java.lang.NumberFormatException: For input string: "conversation!!!"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:441)
        at java.lang.Long.parseLong(Long.java:483)
        at codeu.chat.server.Server.addNewMessage(Server.java:373)
        at codeu.chat.util.PersistentLog.read(PersistentLog.java:55)
        at codeu.chat.ServerMain.runServer(ServerMain.java:135)
        at codeu.chat.ServerMain.main(ServerMain.java:103)
**

**Comment by wrdana** [comment]
@w-sheng , I saw you started working on it, but see the following input and result:
This is my terminal:
![image](https://user-images.githubusercontent.com/6061907/27980173-000bc2fa-634a-11e7-997b-60d53c5600a9.png)

And this is my file
U-ADD 1.2659369757 dana 1499469800960
U-ADD 1.76963575 zohar 1499469804166
U-ADD 1.4172619167 eylon 1499469811230
C-ADD 1.1704854637 1.2659369757 1499469828391 some
M-ADD 1.3929723825 1.2659369757 1.1704854637 1499469835895 wooho!!!!

**Comment by wrdana** [comment]
Hey @w-sheng , this is still happening after I restart the server..
The file has the following 2 lines:
C-ADD 1.2130153829 1.733353770 1500540249383 wow, such an awesome conversation
M-ADD 1.1774371390 1.733353770 1.2130153829 1500540268718  look at me, I'm dancing! Crazy!

But after restarting, I see the following:
>>> c-list
CONVERSATION wow, (UUID:1.2130153829)
>>> c-join wow,
>>> m-list
--- start of conversation ---

USER : 1.733353770
SENT : 20-Jul-2017 10:44:28.718

look

**Comment by w-sheng** [comment]
Hi @wrdana , that's strange since it looks like it works for me after I restart the server.

Here is my file:
U-ADD 1.1831929505 1499227582539 a
C-ADD 1.3201173975 1.1831929505 1499227596766 convo
M-ADD 1.2931026704 1.1831929505 1.3201173975 1499227601031 hi 
M-ADD 1.3675883757 1.1831929505 1.3201173975 1499227604400 hi again
C-ADD 1.820135823 1.1831929505 1499818085254 convo 2
M-ADD 1.344769699 1.1831929505 1.3201173975 1499917003963  hi there
C-ADD 1.630395237 1.1831929505 1499917029859  cool convo
C-ADD 1.1081225067 1.1831929505 1499917463794 another convo

When I run c-list:
![image](https://user-images.githubusercontent.com/25286123/28494419-f5a1969c-6efb-11e7-8c53-55291c88284b.png)

When I run m-list (for convo):

![image](https://user-images.githubusercontent.com/25286123/28494420-09e1fe4e-6efc-11e7-9446-ecd4a2711555.png)

**Comment by w-sheng** [comment]
I'm running my PersistentMessages2 branch and it looks like I already pushed my most recent version. This shouldn't be happening if we're running the same code, right?
